### ISSUE TITLE
gentoo.jp ドメインに対応する

### ISSUE THREAD

**Issue by kjmkznr** [gentoojp/gentoojp.github.io#14]
gentoo.jp ドメインを取得したので、Github Pages のドメインを gentoo.jp に対応しましょう。

ちらっと調べてみたところ、複数ドメインには対応していなさそうなので、
www.gentoo.gr.jp から www.gentoo.jp にリダイレクトが必要そうなのですが、
何か良いプランありますかね。

**Comment by nabeken** [comment]
ついでにwww.gentoo.jpって長いからgentoo.jpにしたいところ。

リダイレクターを適当に作ってherokuにデプロイすれば無料でずっと維持できるかと。

**Comment by nabeken** [comment]
あ、gh-pagesの場合はnakedでは使えなかったですね。。。。

**Comment by kjmkznr** [comment]
そしたら、gentoo.jp はS3にしますか。
費用がかかりすぎるなら、そのときまた考えるということで。

**Comment by nabeken** [comment]
あー、混乱させてすみません。

わざわざS3にしなくても、www.g.jpにして、gh-pagesでよいと思います。

**Comment by kjmkznr** [comment]
了解です。

* www.gentoo.jp -> gh-pages
    - CNAME を書き換え
* www.gentoo.gr.jp -> heroku
    - リダイレクタを適当にデプロイ

では、こんな感じで。

**Comment by nabeken** [comment]
[![LGTM](http://www.lgtm.in/p/yvxIcNgvn)](http://www.lgtm.in/i/yvxIcNgvn)

**Comment by kjmkznr** [comment]
簡単なリダイレクタを作成してみました。
https://www-gentoo-gr-jp.herokuapp.com/
[Repository](https://github.com/gentoojp/www-gentoo-gr-jp-redirector)

週末くらいに、CNAMEファイルの書き換えとDNSレコードの変更をします。

**Comment by nabeken** [comment]
できれば、キャッシュヘッダーつけて欲しいです。permamentでキャッシュ制御なしで飛ばすとchromeは本当に恒久的に残るので当面はキャッシュなしで様子を見たいです。

http://d.hatena.ne.jp/too_young/touch/20110303/1299149420

**Comment by kjmkznr** [comment]
それであれば、キャッシュヘッダーつけるよりも、まずは302を返した方が良くないでしょうか。
 2015/02/11 16:30 "TANABE Ken-ichi" <notifications@github.com>:

**Comment by nabeken** [comment]
それでもよいと思います。

**Comment by kjmkznr** [comment]
CNAME書き換えました。
www.gentoo.gr.jp の方もレコード変更済みです。

**Comment by masatomo** [comment]
ありがとうございます！ 今年はgr.jpの更新しなくていい感じですかね？

**Comment by kjmkznr** [comment]
@masatomo
はい。その予定です！

**Comment by masatomo** [comment]
了解です！ 更新せず。放置します。

**Comment by kjmkznr** [comment]
### ToDo
* [ ] xxx@gentoo.gr.jp を使ってる人にサービス停止を通知する
* [ ] MLのサービス停止の案内を作成する。
* [ ] Google Groups作るかどうか検討する

**Comment by aliceinwire** [comment]
Google Groupsについて
https://groups.google.com/forum/#!forum/gentoojp

**Comment by aliceinwire** [comment]
thx
