### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by mazgi** [gentoojp/gentoojp.github.io#25]
<img width="1224" alt="screen shot 2018-05-06 at 14 56 17" src="https://user-images.githubusercontent.com/194222/39670362-03cd5060-513e-11e8-86c6-a008f5c0f800.png">

**Comment by mazgi** [comment]
<img width="1224" alt="screen shot 2018-05-06 at 14 57 03" src="https://user-images.githubusercontent.com/194222/39670367-1ee549a2-513e-11e8-85c7-3d02ebeea4b5.png">
⏬ ⏬ ⏬ ⏬ Updated ⏬ ⏬ ⏬ ⏬ 
<img width="1224" alt="screen shot 2018-05-06 at 14 57 54" src="https://user-images.githubusercontent.com/194222/39670376-41b3438a-513e-11e8-91ea-f1cb270f705b.png">
<img width="1224" alt="screen shot 2018-05-06 at 14 58 08" src="https://user-images.githubusercontent.com/194222/39670378-4a19751c-513e-11e8-9dd8-5e661b557bfb.png">

**Comment by kjmkznr** [comment]
Nice work!
